# Generated by Django 3.1.2 on 2020-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='order_id',
            new_name='order',
        ),
    ]
