# Generated by Django 3.1.2 on 2020-10-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.CreateModel(
            name='MainSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.subcategory')),
            ],
            options={
                'db_table': 'main_sub_categories',
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_sub',
            field=models.ManyToManyField(through='story.MainSub', to='story.MainCategory'),
        ),
    ]
